name: Update Repository 
on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Update Repository
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'main'
          submodules: true
          
      - name: Prepare Procursus
        uses: localdevice/procursus-action@main
        with:
          packages: apt-utils gzip bzip2 xz-utils zstd
          cache-path: ${{ github.workspace }}/procursus
          
      - name: Push Repo
        run : |
          echo "${{ github.repository }}."
          echo "Runner Ready."
          ls ${{ github.workspace }}
          ./updaterepo.sh
          git config --global user.email "example@mail.com"
          git config --global user.name "Example"
          git add "${{ github.workspace }}"
          git commit -a -m "Push Repo"
          git push
          echo "${{ job.status }}."
